[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Toby Fleming <tobywf@users.noreply.github.com>"]
# categories
# description
# documentation
edition = "2024"
# exclude
# homepage
# include
# keywords
# license
# license-file
publish = false
# readme
# repository
# rust-version
version = "0.0.0"

[workspace.dependencies]
bytemuck = { version = "1.16", features = ["derive", "min_const_generics", "must_cast"] }
color-eyre = { version = "0.6", default-features = false, features = ["track-caller"] }
eyre = { version = "0.6", default-features = false, features = ["auto-install", "track-caller"] }
image = { version = "0.25", default-features = false, features = ["png"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_test = "1.0"
time = { version = "0.3", default-features = false }

# api types only
base64 = "0.22"
# metadata gen only
minijinja = "2.0"
heck = "0.5"
# cli only
clap = { version = "4.5", default-features = false, features = ["std", "derive", "color", "help", "usage", "error-context"] }
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }
zip = { version = "2.1", default-features = false, features = ["deflate"] }
# proc macro/build script only
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2.20"
# anim-names only
fxhash = "0.2.1"

[profile.dev]
opt-level = 1
panic = "unwind"

[profile.dev.package.mech3ax-pixel-ops]
opt-level = 3

[profile.release]
opt-level = 3
panic = "unwind"
lto = true
# the Windows build breaks when this is enabled
# codegen-units = 1
