[package]
name = "mech3ax-metadata-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

autoexamples = false
autobenches = false

[dependencies]
heck.workspace = true
serde.workspace = true
minijinja.workspace = true

mech3ax-api-types = { path = "../api-types" }
mech3ax-metadata-types = { path = "../metadata-types" }
